### ISSUE TITLE
Clarify License

### ISSUE THREAD

**Issue by mikesoule** [skolodyazhnyy/json-stream#15]
@skolodyazhnyy Thank you for this project! Many companies have licensing requirements (must be MIT, Apache, etc.) and require that the license file be included in the package in order for developers to use it in a project. I noticed that the Composer manifest says this is an MIT licensed project. Would you mind adding a license file to the repo?

Example: https://github.com/slimphp/Slim/blob/4.x/LICENSE.md

**Comment by skolodyazhnyy** [comment]
Thanks for bringing this up, i have added license
