### ISSUE TITLE
Update requirements

### ISSUE THREAD

**Issue by jdecool** [skolodyazhnyy/json-stream#18]
First of all, thanks for your work on this library.

I want to update this library requirements and remove [unsupported PHP branches](https://www.php.net/eol).

Are you open to remove support for PHP <= 7.2 ?

I'm also think about migrate CI from Travis to Github Actions.
Are you OK with that ?

**Comment by skolodyazhnyy** [comment]
Sure, looking forward for your PRs.

**Comment by jdecool** [comment]
I close this issue as #19 is merged :) 

Thanks for your reactivity.
