### ISSUE TITLE
Imitate JSON_PRETTY_PRINT and JSON_NUMERIC_CHECK of json_encode

### ISSUE THREAD

**Issue by wmenge** [skolodyazhnyy/json-stream#9]
First of all, great library ;)

Any plans on implementing some flags in the Writer class to better imitate json_encode? I want to replace calls to json_encode for some structures that can become quite large, but I'm relying on those two options.

**Comment by wmenge** [comment]
I have a fix with unit tests in a separate branch. Care to merge it with your repository?

**Comment by skolodyazhnyy** [comment]
@wmenge sure, it's been more than year since you posted comment above 😊, but if you create a PR I will be happy to merge it :)
